Repository AIT-WATCHMAN/rat-pac, pull requests merged in 2020-05, with the labels that each got.

#94 Wbls optics
  data/Watchman/MATERIALS_Watchman.ratdb
  data/Watchman/OPTICS_Watchman.ratdb
  src/physics/src/PhysicsList.cc
Labels: Priority: Critical

#96 Update to optics
  data/Watchman/MATERIALS_Watchman.ratdb
  data/Watchman/OPTICS_Watchman.ratdb
Labels: Hotfix

#91 Reactor IBD Messenger
  data/IBD.ratdb
  mac/watchman_ibd.mac
  src/cmd/CMakeLists.txt
  src/cmd/include/RAT/IBDgenMessenger.hh
  src/cmd/src/IBDgenMessenger.cc
  src/gen/include/RAT/IBDgen.hh
  src/gen/src/IBDgen.cc
  src/gen/src/VertexGen_IBD.cc
  util/geoneutrino2ratdb.py
Labels: Enhancement, Not ready to merge, Refactoring
