Repository AIT-WATCHMAN/rat-pac, pull requests merged in 2020-07, with the labels that each got.

#115 LazyMake
  Makefile
Labels: Enhancement, Hotfix

#84 Add SplitEVDAQ
  data/DAQ.ratdb
  mac/watchman.mac
  src/cmd/src/ProcBlockManager.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/SplitEVDAQProc.hh
  src/daq/src/SplitEVDAQProc.cc
Labels: Enhancement, Ready to merge

#75 Concentrator updates
  data/Watchman/Watchman.geo
  mac/watchman.mac
  mac/watchman_visualize.mac
  mac/watchman_visualize_geofile.mac
  mac/watchman_visualize_geofile_lightcones.mac
  src/geo/src/GeoPMTFactoryBase.cc
  src/geo/src/WatchmanDetectorFactory.cc
  tools/timeRes.C
  tools/timeResiduals.C
Labels: Enhancement

#88 NoiseProc addition
  data/NOISEProc.ratdb
  mac/watchman.mac
  mac/watchman_dev.mac
  src/cmd/src/ProcBlockManager.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/NoiseProc.hh
  src/daq/src/NoiseProc.cc
  src/ds/include/RAT/DS/MCPMT.hh
Labels: Enhancement, Ready to merge

#119 SplitEVDAQ Charge was adding quadratically, this fixes that
  src/daq/src/SplitEVDAQProc.cc
Labels: Hotfix
